class Constant {
  Constant._();

  static const stopMap = <String, String>{
    /* Red Line */
    "The Point": "TPT",
    "Spencer Dock": "SDK",
    "Mayor Square - NCI": "MYS",
    "George's Dock": "GDK",
    "Connolly": "CON",
    "Busáras": "BUS",
    "Abbey Street": "ABB",
    "Jervis": "JER",
    "Four Courts": "FOU",
    "Smithfield": "SMI",
    "Museum": "MUS",
    "Heuston": "HEU",
    "James's": "JAM",
    "Fatima": "FAT",
    "Rialto": "RIA",
    "Suir Road": "SUI",
    "Goldenbridge": "GOL",
    "Drimnagh": "DRI",
    "Blackhorse": "BLA",
    "Bluebell": "BLU",
    "Kylemore": "KYL",
    "Red Cow": "RED",
    "Kingswood": "KIN",
    "Belgard": "BEL",
    "Cookstown": "COO",
    "Hospital": "HOS",
    "Tallaght": "TAL",
    "Fettercairn": "FET",
    "Cheeverstown": "CVN",
    "Citywest Campus": "CIT",
    "Fortunestown": "FOR",
    "Saggart": "SAG",

    /* Green Line */
    "Broombridge": "BRO",
    "Cabra": "CAB",
    "Phibsborough": "PHI",
    "Grangegorman": "GRA",
    "Broadstone - DIT": "BRD",
    "Dominick": "DOM",
    "Parnell": "PAR",
    "O'Connell - Upper": "OUP",
    "O'Connell - GPO": "OGP",
    "Marlborough": "MAR",
    "Westmoreland": "WES",
    "Trinity": "TRY",
    "Dawson": "DAW",
    "St. Stephen's Green": "STS",
    "Harcourt": "HAR",
    "Charlemont": "CHA",
    "Ranelagh": "RAN",
    "Beechwood": "BEE",
    "Cowper": "COW",
    "Milltown": "MIL",
    "Windy Arbour": "WIN",
    "Dundrum": "DUN",
    "Balally": "BAL",
    "Kilmacud": "KIL",
    "Stillorgan": "STI",
    "Sandyford": "SAN",
    "Central Park": "CPK",
    "Glencairn": "GLE",
    "The Gallops": "GAL",
    "Leopardstown Valley": "LEO",
    "Ballyogan Wood": "BAW",
    "Carrickmines": "CCK",
    "Laughanstown": "LAU",
    "Cherrywood": "CHE",
    "Bride's Glen": "BRI",
  };
}
